# Render Blueprint - https://render.com/docs/blueprint-spec
services:
  - type: web
    name: fraud-detection-app
    runtime: python
    region: oregon

    buildCommand: |
      pip install -r requirements.txt
      python data/generate_dataset.py
      python train.py

    startCommand: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
